"""Hardcoded movie catalogue for the CineRater example.

Kept small (25 entries) and self-contained so the demo has zero external
dependencies — no TMDB key, no network calls, deterministic results.
"""

from __future__ import annotations

MOVIES: list[dict] = [
    {"id": 1, "title": "Oppenheimer", "year": 2023, "genre": "Drama",
     "rating": 8.3, "director": "Christopher Nolan",
     "plot": "The story of J. Robert Oppenheimer and the Manhattan Project."},
    {"id": 2, "title": "Mission: Impossible — Dead Reckoning", "year": 2023, "genre": "Action",
     "rating": 7.7, "director": "Christopher McQuarrie",
     "plot": "Ethan Hunt hunts a rogue AI controlling global intelligence networks."},
    {"id": 3, "title": "John Wick: Chapter 4", "year": 2023, "genre": "Action",
     "rating": 7.7, "director": "Chad Stahelski",
     "plot": "Wick uncovers a path to defeating the High Table."},
    {"id": 4, "title": "The Killer", "year": 2023, "genre": "Thriller",
     "rating": 6.8, "director": "David Fincher",
     "plot": "An assassin's job goes wrong, triggering an international manhunt."},
    {"id": 5, "title": "Anatomy of a Fall", "year": 2023, "genre": "Thriller",
     "rating": 7.7, "director": "Justine Triet",
     "plot": "A woman is tried for her husband's death; her blind son is the only witness."},
    {"id": 6, "title": "Past Lives", "year": 2023, "genre": "Romance",
     "rating": 7.9, "director": "Celine Song",
     "plot": "Two childhood friends reunite in New York after 20 years apart."},
    {"id": 7, "title": "Spider-Man: Across the Spider-Verse", "year": 2023, "genre": "Animation",
     "rating": 8.6, "director": "Joaquim Dos Santos",
     "plot": "Miles Morales meets a multiverse team of Spider-People."},
    {"id": 8, "title": "Dune: Part Two", "year": 2024, "genre": "Sci-Fi",
     "rating": 8.5, "director": "Denis Villeneuve",
     "plot": "Paul Atreides unites the Fremen to wage war against House Harkonnen."},
    {"id": 9, "title": "The Zone of Interest", "year": 2023, "genre": "Drama",
     "rating": 7.4, "director": "Jonathan Glazer",
     "plot": "An Auschwitz commandant and his family build a life beside the camp."},
    {"id": 10, "title": "Poor Things", "year": 2023, "genre": "Comedy",
     "rating": 7.8, "director": "Yorgos Lanthimos",
     "plot": "A reanimated woman embarks on a wild journey of self-discovery."},
    {"id": 11, "title": "Killers of the Flower Moon", "year": 2023, "genre": "Crime",
     "rating": 7.6, "director": "Martin Scorsese",
     "plot": "Members of the Osage Nation are murdered for their oil-rich land."},
    {"id": 12, "title": "Civil War", "year": 2024, "genre": "Action",
     "rating": 7.0, "director": "Alex Garland",
     "plot": "Journalists race across a fractured America during a second civil war."},
    {"id": 13, "title": "Challengers", "year": 2024, "genre": "Drama",
     "rating": 7.1, "director": "Luca Guadagnino",
     "plot": "A tennis prodigy turned coach manipulates the careers of two rivals."},
    {"id": 14, "title": "Furiosa: A Mad Max Saga", "year": 2024, "genre": "Action",
     "rating": 7.6, "director": "George Miller",
     "plot": "The origin story of warrior Furiosa before she meets Mad Max."},
    {"id": 15, "title": "The Substance", "year": 2024, "genre": "Horror",
     "rating": 7.3, "director": "Coralie Fargeat",
     "plot": "A fading celebrity uses a black-market drug that creates a younger self."},
    {"id": 16, "title": "Heretic", "year": 2024, "genre": "Horror",
     "rating": 7.0, "director": "Scott Beck",
     "plot": "Two missionaries are trapped in the home of a charismatic stranger."},
    {"id": 17, "title": "Conclave", "year": 2024, "genre": "Thriller",
     "rating": 7.4, "director": "Edward Berger",
     "plot": "Cardinals lock themselves in to elect a new Pope, secrets surface."},
    {"id": 18, "title": "Anora", "year": 2024, "genre": "Drama",
     "rating": 7.6, "director": "Sean Baker",
     "plot": "A sex worker marries the son of a Russian oligarch, then everything unravels."},
    {"id": 19, "title": "Everything Everywhere All at Once", "year": 2022, "genre": "Sci-Fi",
     "rating": 7.8, "director": "Daniels",
     "plot": "A laundromat owner connects with parallel-universe selves to save reality."},
    {"id": 20, "title": "The Banshees of Inisherin", "year": 2022, "genre": "Comedy",
     "rating": 7.7, "director": "Martin McDonagh",
     "plot": "On an Irish island, one friend abruptly ends a lifelong friendship."},
    {"id": 21, "title": "Top Gun: Maverick", "year": 2022, "genre": "Action",
     "rating": 8.2, "director": "Joseph Kosinski",
     "plot": "Maverick trains a new generation of pilots for a near-impossible mission."},
    {"id": 22, "title": "Tar", "year": 2022, "genre": "Drama",
     "rating": 7.4, "director": "Todd Field",
     "plot": "A renowned conductor is consumed by accusations of misconduct."},
    {"id": 23, "title": "Decision to Leave", "year": 2022, "genre": "Thriller",
     "rating": 7.3, "director": "Park Chan-wook",
     "plot": "A detective falls for the prime suspect in a death investigation."},
    {"id": 24, "title": "The Whale", "year": 2022, "genre": "Drama",
     "rating": 7.7, "director": "Darren Aronofsky",
     "plot": "A reclusive English teacher tries to reconnect with his estranged daughter."},
    {"id": 25, "title": "Glass Onion: A Knives Out Mystery", "year": 2022, "genre": "Mystery",
     "rating": 7.1, "director": "Rian Johnson",
     "plot": "Detective Benoit Blanc travels to a tech billionaire's island for a murder game."},
    {"id": 26, "title": "Sinners", "year": 2025, "genre": "Thriller",
     "rating": 7.9, "director": "Ryan Coogler",
     "plot": "Twin brothers return to 1930s Mississippi to open a juke joint, only to attract supernatural evil."},
    {"id": 27, "title": "Materialists", "year": 2025, "genre": "Drama",
     "rating": 7.2, "director": "Celine Song",
     "plot": "A matchmaker navigates love and ambition in New York while torn between two very different men."},
    {"id": 28, "title": "Mickey 17", "year": 2025, "genre": "Sci-Fi",
     "rating": 7.4, "director": "Bong Joon-ho",
     "plot": "A disposable employee on a colonization mission is printed again and again — until two copies exist at once."},
    {"id": 29, "title": "Warfare", "year": 2025, "genre": "Drama",
     "rating": 7.8, "director": "Alex Garland",
     "plot": "A real-time account of a Navy SEAL platoon's harrowing rescue mission in Iraq, told without commentary."},
    {"id": 30, "title": "Black Bag", "year": 2025, "genre": "Thriller",
     "rating": 7.0, "director": "Steven Soderbergh",
     "plot": "An intelligence officer suspects his wife may be the mole inside their own agency."},
]
